apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: payments-system
  annotations:
    azure.workload.identity/client-id: "3f114f66-47cd-4da7-b22b-73cf6d37b243"
  labels:
    azure.workload.identity/use: "true"