apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: acquirer-simulator
  namespace: payments-system
spec:
  host: acquirer-simulator
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
