apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payments-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
    spec:
      containers:
      - name: payment-service
        env:
        - name: AZURE_CLIENT_ID
          value: a11a7c88-abae-4064-b84d-90750b29c01b
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: host
        - name: DB_NAME
          value: payments
        - name: DB_SSLMODE
          value: require
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: payments-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
    spec:
      containers:
      - name: audit-service
        env:
        - name: AZURE_CLIENT_ID
          value: 169f16ce-47d1-4a62-858c-87e047a6deb1
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
        - name: DB_SSLMODE
          value: require
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        - name: AUDIT_HMAC_KEY
          valueFrom:
            secretKeyRef:
              name: audit-secrets
              key: AUDIT_HMAC_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: payments-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
    spec:
      containers:
      - name: ledger-service
        env:
        - name: AZURE_CLIENT_ID
          value: 83d5af08-ec00-4c7c-90ab-44b284e41238
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
        - name: DB_SSLMODE
          value: require
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenization-service
  namespace: payments-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
    spec:
      containers:
      - name: tokenization-service
        env:
        - name: AZURE_CLIENT_ID
          value: f419a134-a73b-47ba-8594-8b690f5d5bb7
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: host
        - name: DB_NAME
          value: tokenization
        - name: DB_SSLMODE
          value: require
        - name: AZURE_KEY_VAULT_URI
          value: https://kv-payments-u3q05i.vault.azure.net/
        - name: AZURE_KEY_NAME
          value: payment-encryption-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-service
  namespace: payments-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
    spec:
      containers:
      - name: merchant-service
        env:
        - name: AZURE_CLIENT_ID
          value: aea19a9f-3087-43ad-979b-a627a531bc3b
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: host
        - name: DB_NAME
          value: merchants
        - name: DB_SSLMODE
          value: require
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acquirer-simulator
  namespace: payments-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
    spec:
      containers:
      - name: acquirer-simulator
        env:
        - name: AZURE_CLIENT_ID
          value: 5125f579-bc77-4f10-bc4b-17aa6d2d04b2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliation-service
  namespace: payments-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
    spec:
      containers:
      - name: reconciliation-service
        env:
        - name: AZURE_CLIENT_ID
          value: 417c95f9-5576-4f2c-a927-47cedf7f3af3
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: host
        - name: DB_NAME
          value: reconciliation
        - name: DB_SSLMODE
          value: require
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: payments-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
    spec:
      containers:
      - name: api-gateway
        env:
        - name: AZURE_CLIENT_ID
          value: fb9aa8e3-9ec0-4efa-a648-b3869232c9ae
